class AmazonPrime{

  public static void main(String[] prime){

    String TopMovies[]={"SALAAR","KALKI","KGF","KGF 2","PUSHPA","JAI HO","DRISHYAM","DRISHYAM 2","WAR","PATHAAN","SULTAN","DHOOM","TANHAJI","SHERSHAAH","BELLBOTTOM"};

    String OriginalSeries[]={"FAMILY MAN","FAMILY MAN 2","MIRZAPUR","MIRZAPUR 2","PANCHAYAT","PANCHAYAT 2","MADE IN HEAVEN","FARZI","ASUR","BREATHE","BREATHE 2","BANDISH BANDITS","JUBILEE","THE BOYS","CITADEL"};

    String ActionMovies[]={"FAST X","JOHN WICK","JOHN WICK 2","JOHN WICK 3","EXTRACTION","EXTRACTION 2","WITHOUT REMORSE","TERMINATOR","MISSION IMPOSSIBLE","TOP GUN","JACK RYAN","SICARIO","MAD MAX","DIE HARD","COMMANDO"};

    String ComedyShows[]={"TWO AND A HALF MEN","FRIENDS","THE OFFICE","MODERN FAMILY","BROOKLYN NINE NINE","PANCHAYAT","HOSTEL DAZE","COMICSTAAN","LOL","MIND THE MALHOTRAS","HAPPY FAMILY","BACHELORS","CAMPUS DIARIES","WHAT THE FOLKS","FLAMES"};

    String ThrillerSeries[]={"JACK RYAN","REACHER","THE TERMINAL LIST","THE NIGHT MANAGER","BREATHE","ASUR","HUNTER","SHE","CRIMINAL JUSTICE","ABHAY","SPECIAL OPS","BARD OF BLOOD","TANDAV","HIT","SUSPENSE"};

    String SouthMovies[]={"RRR","BAAHUBALI","BAAHUBALI 2","KANTARA","VIKRAM","MASTER","JAILER","LEO","DASARA","SITA RAMAM","LOVE STORY","MAGADHEERA","ROBOT","2.0","KGF"};

    String KidsShows[]={"CHHOTA BHEEM","MOTU PATLU","DORAEMON","SHINCHAN","TOM AND JERRY","BEN 10","POKEMON","JUNGLE BOOK","KUNG FU PANDA","MADAGASCAR","CARS","FROZEN","TOY STORY","MINIONS","BOSS BABY"};
  }
}