class DisneyHotstar{

  public static void main(String[] hotstar){

    String MarvelMovies[]={"IRON MAN","IRON MAN 2","IRON MAN 3","THOR","THOR 2","THOR 3","CAPTAIN AMERICA","CIVIL WAR","AVENGERS","AGE OF ULTRON","INFINITY WAR","ENDGAME","BLACK PANTHER","DOCTOR STRANGE","SPIDERMAN"};

    String StarWars[]={"STAR WARS 1","STAR WARS 2","STAR WARS 3","STAR WARS 4","STAR WARS 5","STAR WARS 6","MANDALORIAN","BOBA FETT","OBI WAN","AHSOKA","CLONE WARS","REBELS","BAD BATCH","RESISTANCE","SKELETON CREW"};

    String IndianSeries[]={"SPECIAL OPS","CRIMINAL JUSTICE","CITY OF DREAMS","HUMAN","AARYA","AARYA 2","GRAHAN","OK COMPUTER","THE NIGHT MANAGER","MASOOM","KARM YUDH","KERALA CRIME FILES","DECODERS","OUT OF LOVE","HOSTAGES"};

    String SportsShows[]={"IPL","WORLD CUP","T20 WORLD CUP","IND VS AUS","IND VS ENG","IND VS PAK","PRO KABADDI","ISL","FORMULA 1","WWE","CHAMPIONS LEAGUE","EURO CUP","LA LIGA","BUNDESLIGA","SERIE A"};

    String KidsContent[]={"MICKEY MOUSE","DONALD DUCK","FROZEN","MOANA","CARS","TOY STORY","LION KING","JUNGLE BOOK","ALADDIN","FINDING NEMO","COCO","ENCANTO","BOLT","UP","RATATOUILLE"};

    String ThrillerMovies[]={"PREY","DEADPOOL","LOGAN","ALIEN","PREDATOR","THE MENU","NO EXIT","BAD TIMES","THE HILLS","THE OTHERS","ARMAGEDDON","SIGNS","SPLIT","GLASS","UNBREAKABLE"};

    String SouthMovies[]={"VIKRAM","LEO","MASTER","JAILER","BIGIL","SARKAR","THERI","MERSAL","PETTA","ANNATTHE","DON","MAARI","VIP","KAITHI","ROLEX"};
  }
}