class SonyLiv{

  public static void main(String[] sonyliv){

    String SonyOriginals[]={"SCAM 1992","SCAM 2003","MAHARANI","GULLAK","TABBAR","ROCKET BOYS","ROCKET BOYS 2","AVRODH","AVRODH 2","COLLEGE ROMANCE","CHAMPS","UNDERTAKER","PROJECT 9191","CUBICLES","DHARMVEER"};

    String CrimeSeries[]={"UNDERTAKER","TABBAR","PROJECT 9191","YOUR HONOR","RUDRA","BHAAK","JL50","CHAKRAVYUH","GANGS","BAMFAAD","JAIL","JUSTICE","DARK WEB","TRAPPED","INSPECTOR"};

    String RealityShows[]={"INDIAN IDOL","MASTERCHEF","KBC","INDIAS GOT TALENT","DANCE PLUS","ROADIES","SPLITSVILLA","SUPER DANCER","SHARK TANK","BIG BOSS","INDIAS BEST DANCER","SA RE GA MA PA","THE KAPIL SHOW","COMEDY CIRCUS","ENTERTAINMENT"};

    String SportsContent[]={"WWE RAW","WWE SMACKDOWN","UFC","CRICKET","FOOTBALL","TENNIS","HOCKEY","NBA","NFL","FIFA","CHESS","BADMINTON","TABLE TENNIS","BOXING","OLYMPICS"};

    String ComedyShows[]={"THE KAPIL SHOW","COMEDY CIRCUS","GULLAK","COLLEGE ROMANCE","CHACHA VIDHAYAK","SANDWICH","BACHELORS","FLAMES","MIND THE MALHOTRAS","HUMOROUS","FUNNY DAYS","HOSTEL LIFE","STANDUP","LOL","JOKERS"};

    String ThrillerMovies[]={"TEHRAN","MUMBAI SAGA","BADLA","ANDHADHUN","DRISHYAM","KAABIL","RAAZ","D COMPANY","GANGSTER","SHOOTOUT","DON","DON 2","SPECIAL 26","A WEDNESDAY","KAHANI"};

    String KidsShows[]={"BAL GANESHA","CHHOTA BHEEM","MIGHTY RAJU","ROLL NO 21","KRISH","HANUMAN","LITTLE SINGHAM","SUPER BHEEM","MOTU PATLU","SHIVA","DORAEMON","POKEMON","BEN 10","NINJA HATTORI","SHINCHAN"};
  }
}