class Zee5{

  public static void main(String[] zee5){

    String ZeeOriginals[]={"ABHAY","RANGBAAZ","CODE M","SUNFLOWER","TAISH","KAALI","KAALI 2","POISON","FITRAT","BICCHO KA KHEL","STATE OF SIEGE","THE FINAL CALL","JEET KI ZID","TAJ","MITHYA"};

    String CrimeShows[]={"ABHAY","CODE M","RANGBAAZ","KAALI","POISON","STATE OF SIEGE","THE FINAL CALL","DURANGA","CRIMINAL JUSTICE","D COMPANY","GANGS","UNDERWORLD","MAFIA","POLICE FILES","DARK WEB"};

    String Movies[]={"URI","TANHAJI","SINGHAM","SIMMBA","GOLMAAL","DRISHYAM","BADLA","RAAZ","HAUNTED","1920","WELCOME","HERA PHERI","PHIR HERA PHERI","HOUSEFULL","DABANGG"};

    String SouthContent[]={"RRR","BAAHUBALI","BAAHUBALI 2","MAGADHEERA","KANTARA","PUSHPA","KGF","KGF 2","ROBOT","2.0","VIKRAM","LEO","MASTER","DON","JAILER"};

    String ComedyShows[]={"BHABIJI","HAPPu KI ULTAN","KAPIL SHARMA","TARAK MEHTA","COMEDY NIGHTS","LAUGHTER CHALLENGE","GUPSHUP","FUNNY DAYS","ENTERTAINMENT","MASTI","HAPPY TIME","JOKER","FUN CLUB","LAUGH RIOT","SMILE SHOW"};

    String KidsShows[]={"CHHOTA BHEEM","LITTLE SINGHAM","MOTU PATLU","ROLL NO 21","KRISH","HANUMAN","BAL GANESHA","SUPER BHEEM","SHIVA","DORAEMON","POKEMON","BEN 10","NINJA HATTORI","TOM AND JERRY","MICKEY MOUSE"};

    String RealityShows[]={"SA RE GA MA PA","DANCE INDIA DANCE","INDIAS BEST DRAMEBAAZ","ROADIES","SPLITSVILLA","KBC","SHARK TANK","SUPER DANCER","INDIAN IDOL","BIG BOSS","MASTERCHEF","ENTERTAINMENT","TALENT SHOW","FUN REALITY","LIVE SHOW"};
  }
}